title: Artur Gurgul
email: artur.gurgul@gmail.com
description: >
  Here you can find all about me and my experience in software development.
baseurl: ""
url: "artur.gurgul.pro"
twitter_username: ArturGurgul
github_username:  gurgul

show_drafts: true
comments: true
lsi: false

# highlighter: pygments
# Build settings
markdown: kramdown
#theme: minima

gems:
  - jekyll-feed
  - jekyll-inline-svg

svg:
  optimize: true
  
exclude:
  - Gemfile
  - Gemfile.lock

permalink: none
